default_config:

homeassistant:
  unit_system: metric
  time_zone: Australia/Sydney
  name: Opera House
  latitude: -33.85951127367736
  longitude: 151.22225761413577
  elevation: 0

irrigation_unlimited:
  granularity: 10
  refresh_interval: 10
  testing:
    enabled: true
    speed: 5.0
    output_events: false
    show_log: false
    autoplay: true
    times:
      - name: "1-Evening run"
        start: "2021-01-04 20:05"
        end: "2021-01-04 21:00"
        results: []
      - name: "2-Morning run"
        start: "2021-01-04 05:50"
        end: "2021-01-04 06:00"
        results: []
  controllers:
    - name: 'My Garden'
      enabled: true
      zones:
        - name: 'Front Lawn'
        - name: 'Vege Patch'
        - name: 'Roses'
        - name: 'Back Yard'
      sequences:
        - name: 'Morning'
          duration: '0:10:00'
          delay: '0:00:10'
          schedules:
            - name: 'Sunrise'
              time:
                sun: 'sunrise'
          zones:
            - zone_id: 1
            - zone_id: 2
            - zone_id: 4
        - name: 'Evening'
          duration: '0:10:00'
          delay: '0:00:10'
          schedules:
            - name: 'Dusk'
              time:
                sun: 'sunset'
          zones:
            - zone_id: 1
            - zone_id: [2,3]
            - zone_id: 4
